#!/usr/bin/env python3
from __future__ import annotations

import argparse
import importlib.util
import json
import os
import subprocess
import sys
import tempfile
from pathlib import Path

from playwright.sync_api import sync_playwright


SCRIPT_DIR = Path(__file__).resolve().parent
DESKTOP_ROOT = SCRIPT_DIR.parent
REPO_ROOT = DESKTOP_ROOT.parent
PROJECT_ROOT = REPO_ROOT / "local" / "workspace" / "Horosa-Web-55c75c5b088252fbd718afeffa6d5bcb59254a0c"
DEFAULT_EXE = Path(os.environ.get("LOCALAPPDATA", "")) / "Programs" / "Horosa" / "Horosa.exe"
WINDOWS_SYSTEM_PATH = ";".join([
	str(Path(os.environ.get("SystemRoot", r"C:\Windows")) / "System32"),
	os.environ.get("SystemRoot", r"C:\Windows"),
])


def configure_stdio() -> None:
	for stream in (sys.stdout, sys.stderr):
		reconfigure = getattr(stream, "reconfigure", None)
		if callable(reconfigure):
			try:
				reconfigure(encoding="utf-8", errors="replace")
			except Exception:
				pass


configure_stdio()


def load_module(module_path: Path, module_name: str):
	spec = importlib.util.spec_from_file_location(module_name, module_path)
	if spec is None or spec.loader is None:
		raise RuntimeError(f"unable to load module from {module_path}")
	module = importlib.util.module_from_spec(spec)
	spec.loader.exec_module(module)
	return module


INSTALLED = load_module(SCRIPT_DIR / "installed_desktop_smoke_check.py", "installed_desktop_smoke_check")
LIVE = load_module(SCRIPT_DIR / "desktop_ai_analysis_live_smoke_check.py", "desktop_ai_analysis_live_smoke_check")
WEB_CHECK = load_module(PROJECT_ROOT / "scripts" / "browser_ai_analysis_technique_completeness_check.py", "browser_ai_analysis_technique_completeness_check")
BROWSER_HELPERS = load_module(PROJECT_ROOT / "scripts" / "browser_horosa_targeted_self_check.py", "browser_horosa_targeted_self_check")


def dismiss_blocking_modals(page) -> None:
	for _ in range(8):
		handled = page.evaluate(
			"""
			() => {
			  const isVisible = (node) => !!(node && (node.offsetWidth || node.offsetHeight || node.getClientRects().length));
			  const selectors = [
			    '.ant-modal-root .ant-modal-close',
			    '.ant-notification-notice-close',
			    '.ant-message-notice .anticon-close',
			    '.ant-tour-close',
			  ];
			  for(const selector of selectors){
			    const target = Array.from(document.querySelectorAll(selector)).find(isVisible);
			    if(target){
			      target.click();
			      return true;
			    }
			  }
			  return false;
			}
			"""
		)
		if not handled:
			break
		page.wait_for_timeout(300)


def main() -> None:
	parser = argparse.ArgumentParser()
	parser.add_argument("--exe-path", default=str(DEFAULT_EXE))
	parser.add_argument("--remote-debugging-port", type=int, default=9342)
	parser.add_argument("--json-out", default="")
	args = parser.parse_args()

	exe_path = Path(args.exe_path).resolve()
	if not exe_path.exists():
		raise FileNotFoundError(f"desktop exe not found: {exe_path}")

	work_root = Path(tempfile.mkdtemp(prefix="horosa-technique-complete-desktop-"))
	isolated_localappdata = work_root / "localappdata"
	log_path = isolated_localappdata / "HorosaDesktop" / "logs" / "horosa-desktop.log"
	failure_screenshot = work_root / "desktop-ai-analysis-technique-complete-failure.png"
	result = {
		"status": "FAIL",
		"exePath": str(exe_path),
		"chartTechniques": len(WEB_CHECK.CHART_TECHNIQUES),
		"caseTechniques": len(WEB_CHECK.CASE_TECHNIQUES),
		"allChartOk": False,
		"allCaseOk": False,
		"autoGenerated": {"ok": False},
		"artifacts": {
			"tempRoot": str(work_root),
			"isolatedLocalAppData": str(isolated_localappdata),
		},
		"checks": [],
	}

	if log_path.exists():
		try:
			log_path.unlink()
		except Exception:
			pass
	log_path.parent.mkdir(parents=True, exist_ok=True)
	INSTALLED.kill_running_app()
	INSTALLED.free_port(args.remote_debugging_port)

	env = os.environ.copy()
	env["LOCALAPPDATA"] = str(isolated_localappdata)
	env["PATH"] = WINDOWS_SYSTEM_PATH

	app_proc = subprocess.Popen([str(exe_path), f"--remote-debugging-port={args.remote_debugging_port}"], env=env)
	try:
		runtime_state = LIVE.wait_for_runtime_ready(log_path)
		server_root = str(runtime_state.get("serverRoot") or "").rstrip("/")
		heartbeat = LIVE.wait_for_http_ok(f"{server_root}/heartbeat", timeout_seconds=60) if server_root else {"ok": False}
		if not heartbeat.get("ok"):
			raise RuntimeError(f"backend heartbeat failed: {heartbeat}")
		result["checks"].append({"name": "isolated-runtime-launch", "status": "PASS", "details": runtime_state})
		result["checks"].append({"name": "backend-heartbeat", "status": "PASS", "details": heartbeat})

		if not INSTALLED.wait_for_horosa_window(60):
			raise RuntimeError("desktop app window did not appear")
		INSTALLED.resize_horosa_window(app_proc.pid)
		INSTALLED.wait_for_debug_port(args.remote_debugging_port)

		with sync_playwright() as playwright:
			browser = playwright.chromium.connect_over_cdp(f"http://127.0.0.1:{args.remote_debugging_port}")
			context = browser.contexts[0]
			page = context.pages[0]
			page.add_init_script(WEB_CHECK.build_init_script())
			page.route("**/aianalysis/**", WEB_CHECK.BASE.route_handler)
			page.reload(wait_until="domcontentloaded", timeout=120000)
			BROWSER_HELPERS.wait_for_main_shell(page, timeout_ms=120000)
			page.wait_for_timeout(2500)
			dismiss_blocking_modals(page)
			WEB_CHECK.run_check(page, result)
			result["status"] = "PASS"
			browser.close()
	except Exception:
		try:
			with sync_playwright() as playwright:
				browser = playwright.chromium.connect_over_cdp(f"http://127.0.0.1:{args.remote_debugging_port}")
				page = browser.contexts[0].pages[0]
				page.screenshot(path=str(failure_screenshot), full_page=True)
				browser.close()
				result["artifacts"]["failureScreenshot"] = str(failure_screenshot)
		except Exception:
			pass
		raise
	finally:
		try:
			INSTALLED.close_app_window(app_proc.pid)
			INSTALLED.wait_for_process_exit(30)
		except Exception:
			pass
		try:
			app_proc.kill()
		except Exception:
			pass
	if args.json_out:
		Path(args.json_out).write_text(json.dumps(result, ensure_ascii=False, indent=2), encoding="utf-8")
	print(json.dumps(result, ensure_ascii=False))


if __name__ == "__main__":
	main()
